[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = espidf
monitor_speed = 115200
monitor_filters = time, esp32_exception_decoder
upload_speed = 921600
board_build.partitions = partitions_16mb_ota.csv
board_build.embed_txtfiles = data/ota_page.html
                             data/main_page.html
                             data/style.css

